before:
  hooks:
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm
  goarm:
    - 7
archives:
- format_overrides:
    - goos: windows
      format: zip
  files:
    - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Env.VERSION }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
