name: publish to dockerhub

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: publish to dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: set up buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: login to dockerhub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      -
        name: prepare
        id: prepare
        run: |
            TAG=${GITHUB_REF#refs/tags/}
            echo ::set-output name=tag_name::${TAG}
      
      - name: build (and publish) main image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg VERSION=${{ steps.prepare.outputs.tag_name }} \
            --push \
            -t fopina/cfdd:${{ steps.prepare.outputs.tag_name }} \
            -t fopina/cfdd:latest \
            .
